from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(631, 434)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo1Lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo1Lbl.setFont(font)
        self.titulo1Lbl.setObjectName("titulo1Lbl")
        self.verticalLayout.addWidget(self.titulo1Lbl)
        self.subtituloLbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(True)
        self.subtituloLbl.setFont(font)
        self.subtituloLbl.setObjectName("subtituloLbl")
        self.verticalLayout.addWidget(self.subtituloLbl)
        self.clausulasText = QtWidgets.QPlainTextEdit(Dialog)
        self.clausulasText.setObjectName("clausulasText")
        self.verticalLayout.addWidget(self.clausulasText)
        self.subtitulo2Lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setItalic(True)
        self.subtitulo2Lbl.setFont(font)
        self.subtitulo2Lbl.setObjectName("subtitulo2Lbl")
        self.verticalLayout.addWidget(self.subtitulo2Lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.borrarBtn = QtWidgets.QPushButton(Dialog)
        self.borrarBtn.setObjectName("borrarBtn")
        self.horizontalLayout_2.addWidget(self.borrarBtn)
        self.demostrarBtn = QtWidgets.QPushButton(Dialog)
        self.demostrarBtn.setObjectName("demostrarBtn")
        self.horizontalLayout_2.addWidget(self.demostrarBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo2Lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo2Lbl.setFont(font)
        self.titulo2Lbl.setObjectName("titulo2Lbl")
        self.verticalLayout_2.addWidget(self.titulo2Lbl)
        self.clausulasLbl = QtWidgets.QLabel(Dialog)
        self.clausulasLbl.setObjectName("clausulasLbl")
        self.verticalLayout_2.addWidget(self.clausulasLbl)
        self.processTable = QtWidgets.QTableView(Dialog)
        self.processTable.setObjectName("processTable")
        self.verticalLayout_2.addWidget(self.processTable)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setVisible(True)
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resultadoTitleLbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultadoTitleLbl.setFont(font)
        self.resultadoTitleLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resultadoTitleLbl.setObjectName("resultadoTitleLbl")
        self.horizontalLayout_3.addWidget(self.resultadoTitleLbl)
        self.resultadoLbl = QtWidgets.QLabel(Dialog)
        self.resultadoLbl.setObjectName("resultadoLbl")
        self.horizontalLayout_3.addWidget(self.resultadoLbl)
        self.erroresBtn = QtWidgets.QPushButton(Dialog)
        self.erroresBtn.setObjectName("erroresBtn")
        self.erroresBtn.setVisible(False)
        self.horizontalLayout_3.addWidget(self.erroresBtn)

        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Demostrador de Formulas"))
        self.titulo1Lbl.setText(_translate("Dialog", "Formulas en su forma clausal"))
        self.subtituloLbl.setText(_translate("Dialog", "S={"))
        self.subtitulo2Lbl.setText(_translate("Dialog", "  }"))
        self.borrarBtn.setText(_translate("Dialog", "Borrar"))
        self.demostrarBtn.setText(_translate("Dialog", "Demostrar"))
        self.titulo2Lbl.setText(_translate("Dialog", "Proceso de resolución:"))
        self.clausulasLbl.setText(_translate("Dialog", "S={ }"))
        self.resultadoTitleLbl.setText(_translate("Dialog", "Resultado:"))
        self.resultadoLbl.setText(_translate("Dialog", " Sin entradas"))
        self.erroresBtn.setText(_translate("Dialog", "Ver errores"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.connectEvents()
    Dialog.show()
    sys.exit(app.exec_())

