# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logica.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        scriptDir = os.path.dirname(os.path.realpath(__file__))
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowIcon(QtGui.QIcon(scriptDir + os.path.sep + 'check.ico'))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAnalisis = QtWidgets.QMenu(self.menubar)
        self.menuAnalisis.setObjectName("menuAnalisis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_archivo = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir_archivo.setIcon(icon)
        self.actionAbrir_archivo.setObjectName("actionAbrir_archivo")
        self.actionCerrar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("close.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerrar.setIcon(icon1)
        self.actionCerrar.setObjectName("actionCerrar")
        self.actionDemostrar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resolution.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDemostrar.setIcon(icon2)
        self.actionDemostrar.setObjectName("actionDemostrar")
        self.actionBorrar = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("erase.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBorrar.setIcon(icon3)
        self.actionBorrar.setObjectName("actionBorrar")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.menuArchivo.addAction(self.actionAbrir_archivo)
        self.menuArchivo.addAction(self.actionCerrar)
        self.menuAnalisis.addAction(self.actionDemostrar)
        self.menuAnalisis.addAction(self.actionBorrar)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAnalisis.menuAction())

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo1Lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo1Lbl.setFont(font)
        self.titulo1Lbl.setObjectName("titulo1Lbl")
        self.verticalLayout.addWidget(self.titulo1Lbl)
        self.subtituloLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.subtituloLbl.setFont(font)
        self.subtituloLbl.setObjectName("subtituloLbl")
        self.verticalLayout.addWidget(self.subtituloLbl)
        self.clausulasText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.clausulasText.setObjectName("clausulasText")
        self.verticalLayout.addWidget(self.clausulasText)
        self.subtitulo2Lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.subtitulo2Lbl.setFont(font)
        self.subtitulo2Lbl.setObjectName("subtitulo2Lbl")
        self.verticalLayout.addWidget(self.subtitulo2Lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.borrarBtn = QtWidgets.QPushButton(self.centralwidget)
        self.borrarBtn.setObjectName("borrarBtn")
        self.horizontalLayout_2.addWidget(self.borrarBtn)
        self.demostrarBtn = QtWidgets.QPushButton(self.centralwidget)
        self.demostrarBtn.setObjectName("demostrarBtn")
        self.horizontalLayout_2.addWidget(self.demostrarBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo2Lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo2Lbl.setFont(font)
        self.titulo2Lbl.setObjectName("titulo2Lbl")
        self.verticalLayout_2.addWidget(self.titulo2Lbl)
        self.clausulasLbl = QtWidgets.QLabel(self.centralwidget)
        self.clausulasLbl.setObjectName("clausulasLbl")
        self.verticalLayout_2.addWidget(self.clausulasLbl)
        self.processTable = QtWidgets.QTableView(self.centralwidget)
        self.processTable.setObjectName("processTable")
        self.verticalLayout_2.addWidget(self.processTable)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setVisible(True)
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resultadoTitleLbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultadoTitleLbl.setFont(font)
        self.resultadoTitleLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resultadoTitleLbl.setObjectName("resultadoTitleLbl")
        self.horizontalLayout_3.addWidget(self.resultadoTitleLbl)
        self.resultadoLbl = QtWidgets.QLabel(self.centralwidget)
        self.resultadoLbl.setObjectName("resultadoLbl")
        self.horizontalLayout_3.addWidget(self.resultadoLbl)
        self.erroresBtn = QtWidgets.QPushButton(self.centralwidget)
        self.erroresBtn.setObjectName("erroresBtn")
        self.erroresBtn.setVisible(False)
        self.horizontalLayout_3.addWidget(self.erroresBtn)

        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demostrador de Formulas"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAnalisis.setTitle(_translate("MainWindow", "Analisis"))
        self.actionAbrir_archivo.setText(_translate("MainWindow", "Abrir archivo..."))
        self.actionCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.actionDemostrar.setText(_translate("MainWindow", "Demostrar"))
        self.actionBorrar.setText(_translate("MainWindow", "Borrar"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de ..."))

        self.titulo1Lbl.setText(_translate("MainWindow", "Formulas en su forma clausal"))
        self.subtituloLbl.setText(_translate("MainWindow", "S={"))
        self.subtitulo2Lbl.setText(_translate("MainWindow", "  }"))
        self.borrarBtn.setText(_translate("MainWindow", "Borrar"))
        self.demostrarBtn.setText(_translate("MainWindow", "Demostrar"))
        self.titulo2Lbl.setText(_translate("MainWindow", "Proceso de resolución:"))
        self.clausulasLbl.setText(_translate("MainWindow", "    "))
        self.resultadoTitleLbl.setText(_translate("MainWindow", "Resultado:"))
        self.resultadoLbl.setText(_translate("MainWindow", " Sin entradas"))
        self.erroresBtn.setText(_translate("MainWindow", "Ver errores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

